CREATE TABLE `AppointmentPending` (
	`ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
	`PatientSerNum` INT(11) NOT NULL,
	`sourceName` VARCHAR(255) NOT NULL,
	`appointmentTypeCode` VARCHAR(250) NOT NULL COMMENT 'Appointment Type Code',
	`appointmentTypeDescription` VARCHAR(250) NOT NULL COMMENT 'Appointment Type Description',
	`AppointmentAriaSer` INT(11) NOT NULL,
	`PrioritySerNum` INT(11) NOT NULL,
	`DiagnosisSerNum` INT(11) NOT NULL,
	`Status` VARCHAR(100) NOT NULL,
	`State` VARCHAR(25) NOT NULL,
	`ScheduledStartTime` DATETIME NOT NULL,
	`ScheduledEndTime` DATETIME NOT NULL,
	`ActualStartDate` DATETIME NOT NULL,
	`ActualEndDate` DATETIME NOT NULL,
	`Location` INT(10) NOT NULL DEFAULT '10',
	`RoomLocation_EN` VARCHAR(100) NOT NULL,
	`RoomLocation_FR` VARCHAR(100) NOT NULL,
	`Checkin` TINYINT(4) NOT NULL,
	`ChangeRequest` TINYINT(4) NOT NULL,
	`DateAdded` DATETIME NOT NULL,
	`DateModified` DATETIME NOT NULL,
	`ReadStatus` INT(11) NOT NULL,
	`Level` TINYINT(4) NOT NULL DEFAULT '1',
	`SessionId` TEXT NOT NULL,
	`updatedBy` VARCHAR(255) NOT NULL,
	`LastUpdated` TIMESTAMP NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
	PRIMARY KEY (`ID`) USING BTREE,
	UNIQUE INDEX `UniqueAppointment` (`sourceName`, `AppointmentAriaSer`) USING BTREE,
	INDEX `PatientSerNum` (`PatientSerNum`) USING BTREE,
	INDEX `AppointmentAriaSer` (`AppointmentAriaSer`) USING BTREE,
	INDEX `DiagnosisSerNum` (`DiagnosisSerNum`) USING BTREE,
	INDEX `PrioritySerNum` (`PrioritySerNum`) USING BTREE,
	INDEX `sourceName` (`sourceName`) USING BTREE,
	CONSTRAINT `Appointment_pending_ibfk_1` FOREIGN KEY (`PatientSerNum`) REFERENCES `OpalDB`.`Patient` (`PatientSerNum`) ON UPDATE CASCADE ON DELETE RESTRICT
)
;

CREATE TABLE `AppointmentPendingMH` (
	`AppointmentPendingId` BIGINT(20) NOT NULL,
	`revisionId` BIGINT(20) NOT NULL AUTO_INCREMENT,
	`action` VARCHAR(128) NULL DEFAULT NULL,
	`PatientSerNum` INT(11) NOT NULL,
	`sourceName` VARCHAR(128) NOT NULL,
	`appointmentTypeCode` VARCHAR(250) NOT NULL COMMENT 'Appointment Type Code',
	`appointmentTypeDescription` VARCHAR(250) NOT NULL COMMENT 'Appointment Type Description',
	`AppointmentAriaSer` INT(11) NOT NULL,
	`PrioritySerNum` INT(11) NOT NULL,
	`DiagnosisSerNum` INT(11) NOT NULL,
	`Status` VARCHAR(100) NOT NULL,
	`State` VARCHAR(25) NOT NULL,
	`ScheduledStartTime` DATETIME NOT NULL,
	`ScheduledEndTime` DATETIME NOT NULL,
	`ActualStartDate` DATETIME NOT NULL,
	`ActualEndDate` DATETIME NOT NULL,
	`Location` INT(10) NOT NULL DEFAULT '10',
	`RoomLocation_EN` VARCHAR(100) NOT NULL,
	`RoomLocation_FR` VARCHAR(100) NOT NULL,
	`Checkin` TINYINT(4) NOT NULL,
	`Level` TINYINT(4) NULL DEFAULT NULL,
	`ChangeRequest` TINYINT(4) NOT NULL,
	`PendingDate` DATETIME NOT NULL,
	`ProcessedDate` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
	`ReadStatus` INT(11) NOT NULL,
	`SessionId` TEXT NOT NULL,
	`updatedBy` VARCHAR(255) NOT NULL,
	`LastUpdated` TIMESTAMP NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
	PRIMARY KEY (`AppointmentPendingId`, `revisionId`) USING BTREE,
	INDEX `PatientSerNum` (`PatientSerNum`) USING BTREE,
	INDEX `AppointmentAriaSer` (`AppointmentAriaSer`) USING BTREE,
	INDEX `DiagnosisSerNum` (`DiagnosisSerNum`) USING BTREE,
	INDEX `PrioritySerNum` (`PrioritySerNum`) USING BTREE,
	INDEX `sourceName` (`sourceName`) USING BTREE,
	INDEX `UniqueAppointment` (`sourceName`, `AppointmentAriaSer`) USING BTREE,
	INDEX `revisionId` (`revisionId`) USING BTREE,
	CONSTRAINT `Appointment_pending_mh_ibfk_1` FOREIGN KEY (`PatientSerNum`) REFERENCES `OpalDB`.`Patient` (`PatientSerNum`) ON UPDATE CASCADE ON DELETE RESTRICT
)
;
