"""Updates Patient table defaults and deprecates some fields. Also deprecated one field in Users.

Revision ID: 295142b4e158
Revises: 46d686c984cc
Create Date: 2023-05-31 15:58:12.464986

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '295142b4e158'
down_revision = '46d686c984cc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Add defaults and deprecate fields in the Patient table. Also deprecate one field in Users."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'Patient',
        'PatientAriaSer',
        existing_type=mysql.INTEGER(display_width=11),
        server_default=sa.text('0'),
        comment='Deprecated',
        existing_nullable=False,
    )
    op.alter_column(
        'Patient',
        'PatientId',
        existing_type=mysql.VARCHAR(length=50),
        server_default=sa.text("''"),
        comment='Deprecated',
        existing_nullable=False,
    )
    op.alter_column(
        'Patient',
        'PatientId2',
        existing_type=mysql.VARCHAR(length=50),
        server_default=sa.text("''"),
        comment='Deprecated',
        existing_nullable=False,
    )
    op.alter_column(
        'Patient',
        'Alias',
        existing_type=mysql.VARCHAR(length=100),
        server_default=sa.text("''"),
        existing_nullable=True,
    )
    op.alter_column(
        'Patient',
        'ProfileImage',
        existing_type=mysql.LONGTEXT(),
        comment='Deprecated',
        existing_nullable=True,
    )
    op.alter_column(
        'Patient',
        'TelNum',
        existing_type=mysql.BIGINT(display_width=11),
        server_default=sa.text('0'),
        existing_nullable=True,
    )
    op.alter_column(
        'Patient',
        'StatusReasonTxt',
        existing_type=mysql.TEXT(),
        server_default=sa.text("''"),
        existing_nullable=False,
    )
    op.alter_column(
        'Patient',
        'SessionId',
        existing_type=mysql.TEXT(),
        server_default=sa.text("''"),
        comment='Deprecated',
        existing_nullable=False,
    )
    op.alter_column(
        'Users',
        'SessionId',
        existing_type=mysql.TEXT(),
        server_default=sa.text("''"),
        comment='Deprecated',
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert addition of defaults and deprecated fields in the Patient and Users tables."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'Users',
        'SessionId',
        existing_type=mysql.TEXT(),
        server_default=None,
        comment=None,
        existing_comment='Deprecated',
        existing_nullable=True,
    )
    op.alter_column(
        'Patient',
        'SessionId',
        existing_type=mysql.TEXT(),
        server_default=None,
        comment=None,
        existing_comment='Deprecated',
        existing_nullable=False,
    )
    op.alter_column(
        'Patient',
        'StatusReasonTxt',
        existing_type=mysql.TEXT(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        'Patient',
        'TelNum',
        existing_type=mysql.BIGINT(display_width=11),
        server_default=None,
        existing_nullable=True,
    )
    op.alter_column(
        'Patient',
        'ProfileImage',
        existing_type=mysql.LONGTEXT(),
        comment=None,
        existing_comment='Deprecated',
        existing_nullable=True,
    )
    op.alter_column(
        'Patient',
        'Alias',
        existing_type=mysql.VARCHAR(length=100),
        server_default=None,
        existing_nullable=True,
    )
    op.alter_column(
        'Patient',
        'PatientId2',
        existing_type=mysql.VARCHAR(length=50),
        server_default=None,
        comment=None,
        existing_comment='Deprecated',
        existing_nullable=False,
    )
    op.alter_column(
        'Patient',
        'PatientId',
        existing_type=mysql.VARCHAR(length=50),
        server_default=None,
        comment=None,
        existing_comment='Deprecated',
        existing_nullable=False,
    )
    op.alter_column(
        'Patient',
        'PatientAriaSer',
        existing_type=mysql.INTEGER(display_width=11),
        server_default=None,
        comment=None,
        existing_comment='Deprecated',
        existing_nullable=False,
    )
    # ### end Alembic commands ###
