# SPDX-FileCopyrightText: Copyright (C) 2023 Opal Health Informatics Group at the Research Institute of the McGill University Health Centre <john.kildea@mcgill.ca>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

"""
Deprecate SessionId fields used to store Firebase tokens.

Revision ID: 9f32d05833a5
Revises: 75c66041e347
Create Date: 2023-04-26 17:30:33.369254

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9f32d05833a5'
down_revision = '75c66041e347'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Deprecate SessionId fields previously used by the app and listener to store Firebase tokens."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'EducationalMaterialRating',
        'SessionId',
        existing_type=mysql.TEXT(),
        server_default=sa.text("''"),
        comment='Deprecated',
        existing_nullable=False,
    )
    op.alter_column(
        'Feedback',
        'SessionId',
        existing_type=mysql.TEXT(),
        server_default=sa.text("''"),
        comment='Deprecated',
        existing_nullable=False,
    )
    op.alter_column(
        'PatientActivityLog',
        'SessionId',
        existing_type=mysql.TEXT(),
        server_default=sa.text("''"),
        comment='Deprecated',
        existing_nullable=False,
    )
    op.alter_column(
        'PatientDeviceIdentifier',
        'SessionId',
        existing_type=mysql.TEXT(),
        server_default=sa.text("''"),
        comment='Deprecated',
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert deprecation of SessionId fields."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'PatientDeviceIdentifier',
        'SessionId',
        existing_type=mysql.TEXT(),
        server_default=None,
        comment=None,
        existing_comment='Deprecated',
        existing_nullable=False,
    )
    op.alter_column(
        'PatientActivityLog',
        'SessionId',
        existing_type=mysql.TEXT(),
        server_default=None,
        comment=None,
        existing_comment='Deprecated',
        existing_nullable=False,
    )
    op.alter_column(
        'Feedback',
        'SessionId',
        existing_type=mysql.TEXT(),
        server_default=None,
        comment=None,
        existing_comment='Deprecated',
        existing_nullable=False,
    )
    op.alter_column(
        'EducationalMaterialRating',
        'SessionId',
        existing_type=mysql.TEXT(),
        server_default=None,
        comment=None,
        existing_comment='Deprecated',
        existing_nullable=False,
    )
    # ### end Alembic commands ###
