"""
Add Username column to EducationalMaterialRating table.

Revision ID: 83ccbdfcf3b5
Revises: bcf300b3df7b
Create Date: 2023-05-10 14:17:33.996075

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '83ccbdfcf3b5'
down_revision = 'bcf300b3df7b'
branch_labels = None
depends_on = None


# Ensure that the username values for legacy rows in the EducationalMaterialRating table have been populated.
# This is necessary for rows that used PatientSerNum, before the Username column was added.
username_migration_query = """
    UPDATE EducationalMaterialRating emr
    SET emr.Username = IFNULL((
        SELECT Username FROM Users u
        WHERE u.UserTypeSerNum = emr.PatientSerNum
            AND u.UserType = 'Patient'
    ), '')
    WHERE emr.Username = ''
        AND emr.PatientSerNum IS NOT NULL
    ;
"""


def upgrade() -> None:
    """Add Username column for the person who submitted an educational material rating."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'EducationalMaterialRating',
        sa.Column(
            'Username',
            sa.String(length=255),
            server_default=sa.text("''"),
            nullable=False,
            comment='The username of the person who submitted an educational material rating.',
        ),
    )

    # Ensure the username fields have been populated for legacy rows
    op.execute(username_migration_query)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Drop Username column."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('EducationalMaterialRating', 'Username')
    # ### end Alembic commands ###
