include:
  - template: Auto-DevOps.gitlab-ci.yml

variables:
  TEST_DISABLED: "true"
  DAST_DISABLED: "true"
  POSTGRES_ENABLED: "false"
  

before_script:
  - uname -a
  - docker info
  - echo $SSH_PRIVATE_KEY
  - echo $(date +%s)
  - AUTO_DEVOPS_BUILD_IMAGE_EXTRA_ARGS="--build-arg CACHEBUST=$(date +%s) --ssh ssh_key=$SSH_PRIVATE_KEY"
  - echo $AUTO_DEVOPS_BUILD_IMAGE_EXTRA_ARGS

clone:
  stage: build
  image: 
    name: alpine/git
    entrypoint: [""]
  before_script:
    - git --version
  script:
    ## Create the SSH directory and give it the right permissions
    ##
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - cp $SSH_PRIVATE_KEY ~/.ssh/id_ed25519
    - ls -la ~/.ssh
    - git clone git@gitlab.com:opalmedapps/dbv_opaldb.git