include:
  - template: Auto-DevOps.gitlab-ci.yml

variables:
  TEST_DISABLED: "true"
  DAST_DISABLED: "true"
  POSTGRES_ENABLED: "false"
  

before_script:
  - uname -a
  - docker info
  - echo $SSH_PRIVATE_KEY
  - echo $(date +%s)
  - AUTO_DEVOPS_BUILD_IMAGE_EXTRA_ARGS="--build-arg CACHEBUST=$(date +%s) --ssh ssh_key=$SSH_PRIVATE_KEY"
  - echo $AUTO_DEVOPS_BUILD_IMAGE_EXTRA_ARGS
