image: python:3.9.16-slim-bullseye

# set up
# see: https://docs.gitlab.com/ee/ci/caching/#cache-python-dependencies
# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  TEST_DISABLED: "true"
  DAST_DISABLED: "true"
  POSTGRES_ENABLED: "false"
  CI_APPLICATION_TAG: "$CI_COMMIT_SHA"
  CI_APPLICATION_REPOSITORY: "$CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG/$CI_JOB_NAME"
  AUTO_DEVOPS_BUILD_IMAGE_EXTRA_ARGS: "--build-arg CACHEBUST=$(date +%s) --ssh ssh_key=$SSH_AUTH_SOCK"
  # Alembic Specific
  MARIADB_ROOT_PASSWORD: $MARIADB_ROOT_PASSWORD
  # ensure that user has permissions for test DB to be used by pytest
  MARIADB_USER: $MARIADB_USER
  # alter pip's cache directory to be inside the project directory: https://docs.gitlab.com/ee/ci/caching/#cache-python-dependencies
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"


before_script:
  - uname -a
  - python --version
  - which python
  # install dependencies for mysqlclient
  - apt update && apt-get install -y build-essential libmariadb-dev
  # don't fail if venv is not set up yet (during setup)
  - python -m venv .venv
  - source .venv/bin/activate || true
  # set up env file for DB service
  # use sample env file
  - cp .env.sample .env
  - sed -i "s/^LEGACY_OPAL_DB_NAME=.*/LEGACY_OPAL_DB_NAME=OpalDB/" .env
  - sed -i "s/^LEGACY_QUESTIONNAIRE_DB_NAME=.*/LEGACY_QUESTIONNAIRE_DB_NAME=QuestionnaireDB/" .env
  - sed -i "s/^DOCKER_HOST=.*/DOCKER_HOST=host.docker.internal/" .env
  - sed -i "s/^MARIADB_ROOT_PASSWORD=.*/MARIADB_ROOT_PASSWORD=$MARIADB_PASSWORD/" .env
  - sed -i "s/^MARIADB_USER=.*/MARIADB_USER=$MARIADB_USER/" .env
  - sed -i "s/^MARIADB_PORT=.*/MARIADB_PORT=3307/" .env

setup:
  stage: .pre
  script:
    - apt update && apt-get install -y git
    - python -m venv .venv
    - source .venv/bin/activate
    - pip install --upgrade pip
    - pip install -r requirements/development.txt
  artifacts:
    # pin artifacts to the branch
    # see: https://docs.gitlab.com/ee/ci/pipelines/job_artifacts.html#use-cicd-variables-to-define-the-artifacts-name
    name: $CI_COMMIT_REF_SLUG
    expire_in: 1 week
    paths:
      - .venv
  # Pip's cache doesn't store the python packages
  # https://pip.pypa.io/en/stable/reference/pip_install/#caching
  #
  # If you want to also cache the installed packages, you have to install
  # them in a virtualenv and cache it as well.
  cache:
    # pin artifacts to the branch
    # see: https://docs.gitlab.com/ee/ci/pipelines/job_artifacts.html#use-cicd-variables-to-define-the-artifacts-name
    paths:
      - .cache/pip

flake8:
  stage: test
  script:
    - flake8 --version
    # install plugin to produce code climate report
    - pip install flake8-gl-codeclimate
    # don't fail if there are errors so the result can also be printed to the console for logs
    # fix relative file paths so GitLab is happy and shows the violations properly
    # see: https://github.com/awelzel/flake8-gl-codeclimate/issues/14
    - flake8 --format gl-codeclimate | python -c "import sys; import json; lines = [line.replace('./', '') for line in sys.stdin]; print(json.dumps(json.loads('\n'.join(lines)), indent='\t'));" > gl-code-quality-report.json || true
    # fail if JSON file does not contain empty array
    - cat gl-code-quality-report.json | grep -q "\[\]"
  artifacts:
    when: always
    reports:
      codequality: gl-code-quality-report.json

mypy:
  stage: test
  script:
    # install plugin to produce code climate report
    - pip install mypy-gitlab-code-quality
    - mypy --version
    # export output and don't fail if there are errors
    - mypy opal/ --no-error-summary > mypy-out.txt || true
    - PYTHONHASHSEED=0 mypy-gitlab-code-quality < mypy-out.txt > codequality.json
     # fail if JSON file does not contain empty array
    - cat codequality.json | grep -q "\[\]"
  artifacts:
    when: always
    reports:
      codequality: codequality.json

markdownlint:
  stage: test
  image:
    name: davidanson/markdownlint-cli2:next
    # overwrite default entrypoint (which is a call to markdownlint-cli2)
    entrypoint: [""]
  # this is not a Python script so we don't need to do all this extra stuff
  before_script:
    - markdownlint-cli2 --version
  script:
    # use the config file that is stored outside the root
    - markdownlint-cli2-config .gitlab/markdownlint/.markdownlint-cli2.yaml "**/*.md" "#.venv"
  artifacts:
    when: always
    reports:
      codequality: markdownlint-cli2-codequality.json

# TODO: Add testing service
# test:
#   stage: Test
#   # set up DB service only for the test job since it is not used by others
#   services:
#     - mariadb:10.7.1-focal
#   script:
#     # create additional DBs for legacy DB tests (OpalDB & QuestionnaireDB)
#     - apt update && apt-get install -y default-mysql-client
#     - MYSQL_PWD=$DB_ROOT_PASSWORD mysql -uroot -hmariadb -e "GRANT ALL PRIVILEGES ON \`test_OpalDB\`.* TO \`$MARIADB_USER\`@\`%\`;"
#     - MYSQL_PWD=$DB_ROOT_PASSWORD mysql -uroot -hmariadb -e "GRANT ALL PRIVILEGES ON \`test_QuestionnaireDB\`.* TO \`$MARIADB_USER\`@\`%\`;"
#     - pytest --version
#     - coverage run -m pytest --junitxml=report.xml
#   needs:
#     - job: setup
#   artifacts:
#     when: always
#     reports:
#       junit: report.xml
#     paths:
#       - .coverage

# TODO: Add coverage after tests
# coverage:
#   stage: Test
#   script:
#     - coverage xml
#     - coverage report
#   needs:
#     - job: test
#     - job: setup
#   coverage: '/^TOTAL.+?(\d+\%)$/'
#   artifacts:
#     when: always
#     reports:
#       coverage_report:
#         coverage_format: cobertura
#         path: coverage.xml

build:
  extends: .build
  before_script:
  - eval $(ssh-agent -s)
  - echo $SSH_PRIVATE_KEY | base64 -d | tr -d '\r' | ssh-add -
  - AUTO_DEVOPS_BUILD_IMAGE_EXTRA_ARGS="--build-arg CACHEBUST=$(date +%s) --ssh ssh_key=$SSH_AUTH_SOCK"

# services:
#   - docker:20.10.16-dind
clone:
  stage: build
  image:
    name: alpine/git
    entrypoint: [""]
  before_script:
    - git --version
  script:
    ## Create the SSH directory and give it the right permissions
    ##
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan gitlab.com >> ~/.ssh/known_hosts
    - echo $SSH_PRIVATE_KEY | base64 -d | tr -d '\r' > ~/.ssh/id_ed25519
    - chmod 0700 ~/.ssh/id_ed25519
    - ls -la ~/.ssh
    - git clone git@gitlab.com:opalmedapps/dbv_opaldb.git
  rules:
    - if: '$CI_COMMIT_TAG || $CI_COMMIT_BRANCH'

ritest:
  stage: deploy
  tags:
    - ri-dev
  image: ubuntu:latest
  before_script:
    - uname -a
  script:
    - whoami
    - apt update && apt install -y openssh-client
    # - curl https://lxvmri02.muhcad.muhcfrd.ca/pds?wsdl
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan lxvmri05.muhcad.muhcfrd.ca >> ~/.ssh/known_hosts
    - ssh opalsupt@lxvmri05.muhcad.muhcfrd.ca "whoami; pwd; ls -la ."
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'



include:
  - template: Auto-DevOps.gitlab-ci.yml
  - local: '.gitlab/templates/Build.gitlab-ci.yml'
