# SPDX-FileCopyrightText: Copyright (C) 2023 Opal Health Informatics Group at the Research Institute of the McGill University Health Centre <john.kildea@mcgill.ca>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

exclude: '^(\.vscode/launch\.json|manage\.py)'

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  - id: check-added-large-files
  - id: check-merge-conflict
  - id: check-shebang-scripts-are-executable
  - id: check-json
    # file contains comments
    exclude: ^\.vscode/settings.json$
  - id: check-yaml
    # exclude gitlab-ci.yml because it contains custom tags
    exclude: ^\.gitlab-ci\.yml$
  # check yaml only for syntax (some contain unrecognized tags)
  - id: check-yaml
    name: check-yaml syntax only
    args: ["--unsafe"]
    files: ^\.gitlab-ci\.yml$
  - id: double-quote-string-fixer
  - id: end-of-file-fixer
  - id: trailing-whitespace

- repo: https://github.com/DavidAnson/markdownlint-cli2
  rev: v0.17.2
  hooks:
  - id: markdownlint-cli2

# https://docs.astral.sh/ruff/integrations/#pre-commit
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.9.4
  hooks:
    # Run the linter with fixes
    - id: ruff
      args: [--fix]
    # Run the formatter
    - id: ruff-format

- repo: local
  hooks:
    # use local mypy because mirrors-mypy does not use local mypy config
    - id: mypy
      name: mypy
      description: static type checking
      entry: mypy
      args: ["--config-file=mypy.ini"]
      language: python
      types: [python]
