# SPDX-FileCopyrightText: Copyright (C) 2023 Opal Health Informatics Group at the Research Institute of the McGill University Health Centre <john.kildea@mcgill.ca>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

exclude: '^(\.vscode/launch\.json|manage\.py)'

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  - id: check-added-large-files
  - id: check-merge-conflict
  - id: check-shebang-scripts-are-executable
  - id: check-json
    # file contains comments
    exclude: ^\.vscode/settings.json$
  - id: check-yaml
    # exclude gitlab-ci.yml because it contains custom tags
    exclude: ^\.gitlab-ci\.yml$
  # check yaml only for syntax (some contain unrecognized tags)
  - id: check-yaml
    name: check-yaml syntax only
    args: ["--unsafe"]
    files: ^\.gitlab-ci\.yml$
  - id: double-quote-string-fixer
  - id: end-of-file-fixer
  - id: trailing-whitespace

- repo: https://github.com/abravalheri/validate-pyproject
  rev: v0.24
  hooks:
    - id: validate-pyproject

- repo: https://github.com/executablebooks/mdformat
  rev: 0.7.22
  hooks:
    - id: mdformat
      language: python
      additional_dependencies:
        - mdformat-mkdocs==4.1.2

- repo: https://github.com/astral-sh/uv-pre-commit
  rev: 0.6.9
  hooks:
    - id: uv-lock

- repo: https://github.com/fsfe/reuse-tool
  rev: v5.0.2
  hooks:
    - id: reuse-lint-file

- repo: https://github.com/DavidAnson/markdownlint-cli2
  rev: v0.17.2
  hooks:
  - id: markdownlint-cli2

# https://docs.astral.sh/ruff/integrations/#pre-commit
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.11.1
  hooks:
    # Run the linter with fixes
    - id: ruff
      args: [--fix]
    # Run the formatter
    - id: ruff-format

- repo: local
  hooks:
    # use local mypy because mirrors-mypy does not use local mypy config
    - id: mypy
      name: mypy
      description: static type checking
      entry: mypy
      args: ["--config-file=mypy.ini"]
      language: python
      types: [python]

- repo: https://github.com/crate-ci/typos
  rev: v1.30.2
  hooks:
    - id: typos

# zizmor detects security vulnerabilities in GitHub Actions workflows.
- repo: https://github.com/woodruffw/zizmor-pre-commit
  rev: v1.5.2
  hooks:
    - id: zizmor

- repo: https://github.com/python-jsonschema/check-jsonschema
  rev: 0.31.3
  hooks:
    - id: check-github-workflows
      args: ["--verbose"]
    - id: check-compose-spec
      args: ["--verbose"]
    - id: check-renovate
      args: ["--verbose"]
      additional_dependencies: ['json5']

# `actionlint` hook, for verifying correct syntax in GitHub Actions workflows.
# Some additional configuration for `actionlint` can be found in `.github/actionlint.yaml`.
- repo: https://github.com/rhysd/actionlint
  rev: v1.7.7
  hooks:
    - id: actionlint
      language: golang
      additional_dependencies:
        # actionlint has a shellcheck integration which extracts shell scripts in `run:` steps from GitHub Actions
        # and checks these with shellcheck.
        # see also: https://github.com/rhysd/actionlint/pull/482
        - "github.com/wasilibs/go-shellcheck/cmd/shellcheck@v0.10.0"
