exclude: '^(\.vscode/launch\.json|manage\.py)'

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: check-added-large-files
  - id: check-merge-conflict
  - id: check-shebang-scripts-are-executable
  - id: check-json
  - id: check-yaml
  - id: double-quote-string-fixer
  - id: end-of-file-fixer
  - id: trailing-whitespace

- repo: https://github.com/DavidAnson/markdownlint-cli2
  rev: v0.14.0
  hooks:
  - id: markdownlint-cli2

# https://docs.astral.sh/ruff/integrations/#pre-commit
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.6.8
  hooks:
    # Run the linter with fixes
    - id: ruff
      args: [--fix]
    # Run the formatter
    - id: ruff-format

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.11.2
  hooks:
    - id: mypy
      args: ["--config-file=mypy.ini"]
      additional_dependencies:
        # renovate: datasource=pypi
        - types-PyMySQL==1.1.0.20240524
