# SPDX-FileCopyrightText: Copyright (C) 2025 Opal Health Informatics Group at the Research Institute of the McGill University Health Centre <john.kildea@mcgill.ca>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

[default.extend-words]
muhc = "muhc"
mch = "mch"
# alias in SQL queries
tge = "tge"
# part of SerNum
ser = "ser"
# not worth the cost of fixing
Aggrement = "Aggrement"

[files]
extend-exclude = ["db_management/*/data/**/*.sql"]
