# SPDX-FileCopyrightText: Copyright (C) 2023 Opal Health Informatics Group at the Research Institute of the McGill University Health Centre <john.kildea@mcgill.ca>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

services:
  db:
    volumes:
      - ./certs:/certs
      - ./config/ssl.cnf:/etc/mysql/conf.d/ssl.cnf
  adminer:
    volumes:
      - ./certs:/certs
      - ./config/adminer-login-ssl.php:/var/www/html/plugins-enabled/adminer-login-ssl.php

  app:
    volumes:
      - ./certs:/certs
