version: '3'

services:
  db:
    image: mariadb:10.6.4-focal
    ports:
      - 3306:3306
    volumes:
      - $PWD/db:/docker-entrypoint-initdb.d
    environment:
      - MARIADB_ROOT_PASSWORD=super-duper-secret-password
      - MARIADB_USER=opal
      - MARIADB_PASSWORD=super-duper-more-secretive-password

  adminer:
    image: adminer:4.8.1-standalone
    depends_on:
      - db
    ports:
      - 8090:8080
