version: '3'

services:
  db:
    container_name: opal-dbs
    image: mariadb:10.6.11-focal
    ports:
      - ${MARIADB_PORT}:3306
    volumes:
      - ./db-scripts:/docker-entrypoint-initdb.d
      - ./config/mariadb.cnf:/etc/mysql/conf.d/opal.cnf
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
      - MARIADB_GUEST_USER=${MARIADB_GUEST_USER}
      - MARIADB_GUEST_PASSWORD=${MARIADB_GUEST_PASSWORD}
      - TZ=EST5EDT
  dbv:
    container_name: dbv-apps
    build:
      context: .
      ssh:
        # require the SSH_KEY_PATH varialbe to be set and not empty
        # see: https://docs.docker.com/compose/environment-variables/#substitute-environment-variables-in-compose-files
        - ssh_key=${SSH_KEY_PATH:?err}
    image: opalmedapps/dbv:latest
    depends_on:
      - db
    ports:
      - ${PHP_PORT}:8080
    volumes:
      # maintain current revision of DBVs across DBV updates
      # - ./revisions/opaldb:/var/www/html/dbv/dbv_opaldb/data/meta
      - ./revisions/questionnairedb:/var/www/html/dbv/dbv_questionnairedb/data/meta
      - ./revisions/registerdb:/var/www/html/dbv/dbv_registerdb/data/meta
      - ./revisions/opalreportdb:/var/www/html/dbv/dbv_opalreportdb/data/meta
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
      - MARIADB_PORT=${MARIADB_PORT}
      - PHP_PORT=${PHP_PORT}

  adminer:
    container_name: adminer
    image: adminer:4.8.1-standalone
    depends_on:
      - db
    ports:
      - ${ADMINER_PORT}:8080

  alembic:
    container_name: alembic-app
    image: alembic:latest
    build:
      context: .
      dockerfile: alembic.Dockerfile
    volumes:
      - ./alembic/opaldb:/app/Alembic/opaldb
    ports:
      - 8092:8092
    depends_on:
      - db
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
      - MARIADB_PORT=${MARIADB_PORT}
      - PHP_PORT=${PHP_PORT}
      - DOCKER_HOST=${DOCKER_HOST}
      - LEGACY_OPAL_DB_NAME=${LEGACY_OPAL_DB_NAME}
      - LEGACY_QUESTIONNAIRE_DB_NAME=${LEGACY_QUESTIONNAIRE_DB_NAME}
