services:
  db:
    container_name: opal-dbs
    image: mariadb:10.6.15-focal
    ports:
      - ${MARIADB_EXTERNAL_PORT}:3306
    volumes:
      - ./db-scripts:/docker-entrypoint-initdb.d
      - ./config/mariadb.cnf:/etc/mysql/conf.d/opal.cnf
    environment:
      - MARIADB_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
      - MARIADB_USER=${DATABASE_USER}
      - MARIADB_PASSWORD=${DATABASE_PASSWORD}
      - MARIADB_GUEST_USER=${DATABASE_GUEST_USER}
      - MARIADB_GUEST_PASSWORD=${DATABASE_GUEST_PASSWORD}
      - TZ=EST5EDT
  dbv:
    container_name: dbv-apps
    build:
      context: .
      ssh:
        # require the SSH_KEY_PATH varialbe to be set and not empty
        # see: https://docs.docker.com/compose/environment-variables/#substitute-environment-variables-in-compose-files
        - ssh_key=${SSH_KEY_PATH:?err}
    image: opalmedapps/dbv:latest
    depends_on:
      - db
    ports:
      - ${PHP_PORT}:8080
    volumes:
      # maintain current revision of DBVs across DBV updates
      - ./revisions/opaldb:/var/www/html/dbv/dbv_opaldb/data/meta
      - ./revisions/opalreportdb:/var/www/html/dbv/dbv_opalreportdb/data/meta
    env_file:
      - .env
    environment:
      - TZ=EST5EDT

  adminer:
    container_name: adminer
    image: adminer:4.8.1-standalone
    depends_on:
      - db
    ports:
      - ${ADMINER_PORT}:8080
    env_file:
      - .env

  alembic:
    container_name: alembic-app
    image: opalmedapps/alembic:latest
    build:
      context: .
      dockerfile: alembic.Dockerfile
    volumes:
      - ./certs:/certs
      - ./alembic.ini:/app/alembic.ini
      - ./db_management:/app/db_management
    depends_on:
      - db
      # TODO: Enable a health check on db container before alembic runs to fix
      #       "Can't connect to MySQL server on 'db' (115)" error thrown by alembic.
      #       This error occurs when alembic tries to run before db is finished creating the dbs.
      #       If the error is encountered, simply re-start the containers a second time and alembic will work.
    env_file:
      - .env
    #command: /app/alembic-upgrade.sh  # Upgrade legacy dbs with alembic
