# ruff settings
# https://docs.astral.sh/ruff/settings/

# https://docs.astral.sh/ruff/settings/#line-length
line-length = 120
# https://docs.astral.sh/ruff/settings/#show-fixes
show-fixes = true
# enable preview mode
# https://docs.astral.sh/ruff/preview/
preview = true

# https://docs.astral.sh/ruff/settings/#lint
[lint]
# https://docs.astral.sh/ruff/settings/#lint_select
# Rules: https://docs.astral.sh/ruff/rules/
select = [
    # pycodestyle
    # https://docs.astral.sh/ruff/rules/#pycodestyle-e-w
    "E",
    "W",
    # Pyflakes
    # https://docs.astral.sh/ruff/rules/#pyflakes-f
    "F",
    # mccabe
    # https://docs.astral.sh/ruff/rules/#mccabe-c90
    "C90",
    # isort
    # https://docs.astral.sh/ruff/rules/#isort-i
    "I",
    # pep8-naming
    # https://docs.astral.sh/ruff/rules/#pep8-naming-n
    "N",
    # pydocstyle
    # https://docs.astral.sh/ruff/rules/#pydocstyle-d
    "D",
    # pyupgrade
    # https://docs.astral.sh/ruff/rules/#pyupgrade-up
    "UP",
    # flake8-bandit
    # https://docs.astral.sh/ruff/rules/#flake8-bandit-s
    "S",
    # flake8-boolean-trap
    # https://docs.astral.sh/ruff/rules/#flake8-boolean-trap-fbt
    "FBT",
    # flake8-bugbear
    # https://docs.astral.sh/ruff/rules/#flake8-bugbear-b
    "B",
    # flake8-builtins
    # https://docs.astral.sh/ruff/rules/#flake8-builtins-a
    "A",
    # flake8-comprehensions
    # https://docs.astral.sh/ruff/rules/#flake8-comprehensions-c4
    "C4",
    # flake8-datetimez
    # https://docs.astral.sh/ruff/rules/#flake8-datetimez-dtz
    "DTZ",
    # flake8-errmsg (EM)
    # https://docs.astral.sh/ruff/rules/#flake8-errmsg-em
    "EM",
    # flake8-executable
    # https://docs.astral.sh/ruff/rules/#flake8-executable-exe
    "EXE",
    # flake8-implicit-str-concat
    # https://docs.astral.sh/ruff/rules/#flake8-implicit-str-concat-isc
    "ISC",
    # flake8-no-pep420
    # https://docs.astral.sh/ruff/rules/#flake8-no-pep420-inp
    "INP",
    # flake8-pytest-style
    # https://docs.astral.sh/ruff/rules/#flake8-pytest-style-pt
    "PT",
    # flake8-quotes
    # https://docs.astral.sh/ruff/rules/#flake8-quotes-q
    "Q",
    # flake8-return
    # https://docs.astral.sh/ruff/rules/#flake8-return-ret
    "RET",
    # flake8-simplify
    # https://docs.astral.sh/ruff/rules/#flake8-simplify-sim
    "SIM",
    # flake8-tidy-imports
    # https://docs.astral.sh/ruff/rules/#flake8-tidy-imports-tid
    "TID",
    # flake8-type-checking
    # https://docs.astral.sh/ruff/rules/#flake8-type-checking-tch
    "TCH",
    # flake8-unused-arguments (ARG)
    # https://docs.astral.sh/ruff/rules/#flake8-unused-arguments-arg
    "ARG",
    # flake8-use-pathlib
    # https://docs.astral.sh/ruff/rules/#flake8-use-pathlib-pth
    "PTH",
    # eradicate
    # https://docs.astral.sh/ruff/rules/#eradicate-era
    "ERA",
    # pylint
    # https://docs.astral.sh/ruff/rules/#pylint-pl
    "PL",
    # tryceratops
    # https://docs.astral.sh/ruff/rules/#tryceratops-try
    "TRY",
    # perflint
    # https://docs.astral.sh/ruff/rules/#perflint-perf
    "PERF",
    # pydoclint (DOC)
    # https://docs.astral.sh/ruff/rules/#pydoclint-doc
    "DOC",
    # ruff
    # https://docs.astral.sh/ruff/rules/#ruff-specific-rules-ruf
    "RUF",
]
# https://docs.astral.sh/ruff/settings/#lint_ignore
ignore = [
    # Skip missing docstring in public package
    "D104",
    # Skip docstring summary on first line (prefer D213)
    "D212",
    # Skip no blank line before class (prefer D203)
    "D211",
    "FBT001",
    "FBT002",
    # explicit is better than implicit (string concatenation)
    "ISC003",
]

extend-select = [
    # This rule is disabled by default (https://docs.astral.sh/ruff/rules/multi-line-summary-second-line/)
    "D213",
]

[lint.per-file-ignores]
"**/versions/*" = [
    # allow long lines
    "E501",
    # invalid module name
    "N999",
    # too many statements
    "PLR0915",
]
"**/models.py" = [
    # allow missing docstring in public module
    "D100",
    # allow missing docstring in public class
    "D101",
    # allow long lines
    "E501",
    # allow variable mixed case in class scope
    "N815",
    # allow variable mixed case in global scope
    "N816",
]
"**/revision_data/*" = [
    # allow long lines
    "E501",
]
"**/tests/*" = [
    # don't require docstrings in tests
    "D",
    # allow assert
    "S101",
    # allow magic values
    "PLR2004",
]

# https://docs.astral.sh/ruff/settings/#lintpydocstyle
[lint.pydocstyle]
# Use Google-style docstrings.
convention = "google"

# https://docs.astral.sh/ruff/settings/#lintflake8-quotes
[lint.flake8-quotes]
inline-quotes = "single"

# https://docs.astral.sh/ruff/settings/#lintisort
[lint.isort]
known-first-party = ["db_management"]

# https://docs.astral.sh/ruff/settings/#format
[format]
quote-style = "single"
indent-style = "space"
