# SPDX-FileCopyrightText: Copyright (C) 2023 Opal Health Informatics Group at the Research Institute of the McGill University Health Centre <john.kildea@mcgill.ca>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

"""
Initial schema generation.

Revision ID: 07f067b25688
Revises:
Create Date: 2023-06-05 20:20:36.776310

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '07f067b25688'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Generate tables."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'CronLog',
        sa.Column('ID', mysql.BIGINT(display_width=20), nullable=False),
        sa.Column('ReStartTime', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('ID'),
    )
    op.create_table(
        'KioskLog',
        sa.Column('KioskLogId', mysql.INTEGER(display_width=11), nullable=False),
        sa.Column('Timestamp', sa.DateTime(), server_default=sa.text('current_timestamp()'), nullable=False),
        sa.Column('KioskInput', sa.String(length=50), nullable=True),
        sa.Column('KioskLocation', sa.String(length=50), server_default=sa.text("''"), nullable=False),
        sa.Column('PatientDestination', sa.String(length=100), nullable=True),
        sa.Column('CenterImage', sa.String(length=100), nullable=True),
        sa.Column('ArrowDirection', sa.String(length=50), nullable=True),
        sa.Column('DisplayMessage', sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint('KioskLogId'),
    )
    op.create_table(
        'SmsLog',
        sa.Column('SmsLogSer', mysql.INTEGER(display_width=11), nullable=False),
        sa.Column('SmsTimestamp', sa.DateTime(), nullable=False),
        sa.Column('ProcessedTimestamp', sa.DateTime(), server_default=sa.text('current_timestamp()'), nullable=False),
        sa.Column('Result', sa.Text(), server_default=sa.text("''"), nullable=False),
        sa.Column('Action', sa.Enum('SENT', 'RECEIVED'), nullable=False),
        sa.Column('Service', sa.String(length=50), server_default=sa.text("''"), nullable=False),
        sa.Column('MessageId', sa.String(length=50), server_default=sa.text("''"), nullable=False),
        sa.Column('ServicePhoneNumber', sa.String(length=50), server_default=sa.text("''"), nullable=False),
        sa.Column('ClientPhoneNumber', sa.String(length=50), server_default=sa.text("''"), nullable=False),
        sa.Column('Message', sa.Text(), server_default=sa.text("''"), nullable=False),
        sa.PrimaryKeyConstraint('SmsLogSer'),
    )
    op.create_index('Service', 'SmsLog', ['Service', 'MessageId'], unique=True)
    op.create_index(op.f('ix_SmsLog_ProcessedTimestamp'), 'SmsLog', ['ProcessedTimestamp'], unique=False)
    op.create_index(op.f('ix_SmsLog_SmsTimestamp'), 'SmsLog', ['SmsTimestamp'], unique=False)
    op.create_table(
        'VirtualWaitingRoomLog',
        sa.Column('VirtualWaitingRoomLogSer', mysql.INTEGER(display_width=11), nullable=False),
        sa.Column('DateTime', sa.DateTime(), nullable=False),
        sa.Column('FileName', sa.String(length=255), server_default=sa.text("''"), nullable=False),
        sa.Column('Identifier', sa.String(length=255), server_default=sa.text("''"), nullable=False),
        sa.Column('Type', sa.String(length=255), server_default=sa.text("''"), nullable=False),
        sa.Column('Message', sa.Text(), server_default=sa.text("''"), nullable=False),
        sa.Column(
            'LastUpdated',
            sa.TIMESTAMP(),
            server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint('VirtualWaitingRoomLogSer'),
    )
    op.create_index(op.f('ix_VirtualWaitingRoomLog_DateTime'), 'VirtualWaitingRoomLog', ['DateTime'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Delete tables."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_VirtualWaitingRoomLog_DateTime'), table_name='VirtualWaitingRoomLog')
    op.drop_table('VirtualWaitingRoomLog')
    op.drop_index(op.f('ix_SmsLog_SmsTimestamp'), table_name='SmsLog')
    op.drop_index(op.f('ix_SmsLog_ProcessedTimestamp'), table_name='SmsLog')
    op.drop_index('Service', table_name='SmsLog')
    op.drop_table('SmsLog')
    op.drop_table('KioskLog')
    op.drop_table('CronLog')
    # ### end Alembic commands ###
