"""‘Default_value_of_AliasName_of_DiagnosisTranslation’

Revision ID: 357c4c529cab
Revises: f231a7f6f6ca
Create Date: 2023-05-24 14:39:58.806111

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '357c4c529cab'
down_revision = 'f231a7f6f6ca'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('DiagnosisTranslation', 'AliasName',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('DiagnosisTranslation', 'AliasName',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###
