"""KA.various-default-fixes-and-pdi

Revision ID: 75c66041e347
Revises: 7a189846a0f5
Create Date: 2023-03-30 15:49:58.952989

"""
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision = '75c66041e347'
down_revision = '7a189846a0f5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Add server defaults to several tables and update PDI with new Username-based workflow.

    The following tickets are covered by this migration:
        https://o-hig.atlassian.net/browse/QSCCD-764?search_id=2b5fc479-a6f8-4797-8151-11caae59b6fc
        https://o-hig.atlassian.net/browse/QSCCD-913?search_id=7e0e6b16-c8f4-45f1-ab5a-c7b8afc2ec22
        https://o-hig.atlassian.net/browse/QSCCD-906?search_id=889612d5-4d8f-4705-a19d-7886ad09ae5b
        https://o-hig.atlassian.net/browse/QSCCD-108?search_id=d5779646-9004-40ac-9a59-d156da704b93
        https://o-hig.atlassian.net/browse/QSCCD-733?search_id=79b4d358-9972-41c1-80e3-c4070d2f7dc7
        https://o-hig.atlassian.net/browse/QSCCD-988?search_id=6f002bd3-4aca-41a0-8eb0-9c565625c97e
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'Alias',
        'AliasUpdate',
        existing_type=mysql.INTEGER(display_width=11),
        server_default=sa.text('0'),
        existing_nullable=False,
    )
    op.alter_column(
        'AppointmentPendingMH',
        'AppointmentPendingId',
        existing_type=mysql.BIGINT(display_width=20),
        server_default=sa.text('0'),
        existing_nullable=False,
    )
    op.add_column(
        'PatientDeviceIdentifier',
        sa.Column(
            'Username',
            sa.String(length=255),
            server_default=sa.text("''"),
            nullable=False,
        ),
    )
    op.add_column(
        'PatientDeviceIdentifier',
        sa.Column(
            'SecurityAnswer',
            sa.String(length=256),
            server_default=sa.text("''"),
            nullable=False,
        ),
    )
    op.alter_column(
        'PatientDeviceIdentifier',
        'PatientSerNum',
        existing_type=mysql.INTEGER(display_width=11),
        server_default=sa.text('0'),
        comment='Deprecated',
        existing_nullable=False,
    )
    op.drop_constraint('PatientDeviceIdentifier_ibfk_3', 'PatientDeviceIdentifier', type_='foreignkey')
    op.drop_constraint('PatientDeviceIdentifier_ibfk_2', 'PatientDeviceIdentifier', type_='foreignkey')
    op.alter_column(
        'Resource',
        'ResourceAriaSer',
        existing_type=mysql.INTEGER(display_width=11),
        server_default=sa.text('0'),
        existing_nullable=False,
    )
    op.alter_column(
        'masterSourceAlias',
        'deletedBy',
        existing_type=mysql.VARCHAR(length=255),
        server_default=sa.text("''"),
        existing_comment='username of who marked the record to be deleted',
        existing_nullable=False,
    )
    op.alter_column(
        'patientStudy',
        'readStatus',
        existing_type=mysql.INTEGER(display_width=11),
        server_default=sa.text('0'),
        existing_comment='Patient read status for this consent form.',
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Backwards migration, remove above changes."""
    op.alter_column(
        'patientStudy',
        'readStatus',
        existing_type=mysql.INTEGER(display_width=11),
        server_default=None,
        existing_comment='Patient read status for this consent form.',
        existing_nullable=False,
    )
    op.alter_column(
        'masterSourceAlias',
        'deletedBy',
        existing_type=mysql.VARCHAR(length=255),
        server_default=None,
        existing_comment='username of who marked the record to be deleted',
        existing_nullable=False,
    )
    op.alter_column(
        'Resource',
        'ResourceAriaSer',
        existing_type=mysql.INTEGER(display_width=11),
        server_default=None,
        existing_nullable=False,
    )
    op.create_foreign_key(
        'PatientDeviceIdentifier_ibfk_3',
        'PatientDeviceIdentifier',
        'Patient',
        ['PatientSerNum'],
        ['PatientSerNum'],
        onupdate='CASCADE',
    )
    op.create_foreign_key(
        'PatientDeviceIdentifier_ibfk_2',
        'PatientDeviceIdentifier',
        'SecurityAnswer',
        ['SecurityAnswerSerNum'],
        ['SecurityAnswerSerNum'],
        onupdate='CASCADE',
    )
    op.alter_column(
        'PatientDeviceIdentifier',
        'PatientSerNum',
        existing_type=mysql.INTEGER(display_width=11),
        server_default=None,
        comment=None,
        existing_comment='Deprecated',
        existing_nullable=False,
    )
    op.drop_column('PatientDeviceIdentifier', 'SecurityAnswer')
    op.drop_column('PatientDeviceIdentifier', 'Username')
    op.alter_column(
        'AppointmentPendingMH',
        'AppointmentPendingId',
        existing_type=mysql.BIGINT(display_width=20),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        'Alias',
        'AliasUpdate',
        existing_type=mysql.INTEGER(display_width=11),
        server_default=None,
        existing_nullable=False,
    )
