"""Add default value for alert deletedBy

Revision ID: 7ebe01c0c5e0
Revises: bcf300b3df7b
Create Date: 2023-05-19 16:57:01.636308

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7ebe01c0c5e0'
down_revision = 'bcf300b3df7b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('definitionTable',
    sa.Column('ID', mysql.BIGINT(display_width=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('ID'),
    schema='QuestionnaireDB'
    )
    op.create_table('dictionary',
    sa.Column('ID', mysql.BIGINT(display_width=20), nullable=False),
    sa.Column('tableId', mysql.BIGINT(display_width=20), nullable=False),
    sa.Column('languageId', mysql.BIGINT(display_width=20), nullable=False),
    sa.Column('contentId', mysql.BIGINT(display_width=20), nullable=False),
    sa.Column('content', mysql.MEDIUMTEXT(), nullable=False),
    sa.Column('deleted', mysql.TINYINT(display_width=4), server_default=sa.text('0'), nullable=False),
    sa.Column('deletedBy', sa.String(length=255), nullable=True),
    sa.Column('creationDate', sa.DateTime(), nullable=False),
    sa.Column('createdBy', sa.String(length=255), nullable=False),
    sa.Column('lastUpdated', sa.TIMESTAMP(), server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'), nullable=False),
    sa.Column('updatedBy', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['languageId'], ['QuestionnaireDB.language.ID'], ),
    sa.ForeignKeyConstraint(['tableId'], ['QuestionnaireDB.definitionTable.ID'], ),
    sa.PrimaryKeyConstraint('ID'),
    schema='QuestionnaireDB'
    )
    op.create_index(op.f('ix_QuestionnaireDB_dictionary_contentId'), 'dictionary', ['contentId'], unique=False, schema='QuestionnaireDB')
    op.create_index(op.f('ix_QuestionnaireDB_dictionary_deleted'), 'dictionary', ['deleted'], unique=False, schema='QuestionnaireDB')
    op.create_index(op.f('ix_QuestionnaireDB_dictionary_languageId'), 'dictionary', ['languageId'], unique=False, schema='QuestionnaireDB')
    op.create_index(op.f('ix_QuestionnaireDB_dictionary_tableId'), 'dictionary', ['tableId'], unique=False, schema='QuestionnaireDB')
    op.create_table('language',
    sa.Column('ID', mysql.BIGINT(display_width=20), nullable=False),
    sa.Column('isoLang', sa.String(length=2), nullable=False),
    sa.Column('name', mysql.BIGINT(display_width=20), nullable=False),
    sa.Column('deleted', mysql.TINYINT(display_width=4), server_default=sa.text('0'), nullable=False),
    sa.Column('deletedBy', sa.String(length=255), nullable=False),
    sa.Column('creationDate', sa.DateTime(), nullable=False),
    sa.Column('createdBy', sa.String(length=255), nullable=False),
    sa.Column('lastUpdated', sa.TIMESTAMP(), server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'), nullable=False),
    sa.Column('updatedBy', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['name'], ['QuestionnaireDB.dictionary.contentId'], ),
    sa.PrimaryKeyConstraint('ID'),
    schema='QuestionnaireDB'
    )
    op.create_index(op.f('ix_QuestionnaireDB_language_deleted'), 'language', ['deleted'], unique=False, schema='QuestionnaireDB')
    op.create_index(op.f('ix_QuestionnaireDB_language_name'), 'language', ['name'], unique=False, schema='QuestionnaireDB')
    op.create_table('purpose',
    sa.Column('ID', mysql.BIGINT(display_width=20), nullable=False),
    sa.Column('title', mysql.BIGINT(display_width=20), nullable=False),
    sa.Column('description', mysql.BIGINT(display_width=20), nullable=False),
    sa.ForeignKeyConstraint(['description'], ['QuestionnaireDB.dictionary.contentId'], ),
    sa.ForeignKeyConstraint(['title'], ['QuestionnaireDB.dictionary.contentId'], ),
    sa.PrimaryKeyConstraint('ID'),
    schema='QuestionnaireDB'
    )
    op.create_index(op.f('ix_QuestionnaireDB_purpose_description'), 'purpose', ['description'], unique=False, schema='QuestionnaireDB')
    op.create_index(op.f('ix_QuestionnaireDB_purpose_title'), 'purpose', ['title'], unique=False, schema='QuestionnaireDB')
    op.create_table('respondent',
    sa.Column('ID', mysql.BIGINT(display_width=20), nullable=False),
    sa.Column('title', mysql.BIGINT(display_width=20), nullable=False),
    sa.Column('description', mysql.BIGINT(display_width=20), nullable=False),
    sa.ForeignKeyConstraint(['description'], ['QuestionnaireDB.dictionary.contentId'], ),
    sa.ForeignKeyConstraint(['title'], ['QuestionnaireDB.dictionary.contentId'], ),
    sa.PrimaryKeyConstraint('ID'),
    schema='QuestionnaireDB'
    )
    op.create_index(op.f('ix_QuestionnaireDB_respondent_description'), 'respondent', ['description'], unique=False, schema='QuestionnaireDB')
    op.create_index(op.f('ix_QuestionnaireDB_respondent_title'), 'respondent', ['title'], unique=False, schema='QuestionnaireDB')
    op.create_table('questionnaire',
    sa.Column('ID', mysql.BIGINT(display_width=20), nullable=False),
    sa.Column('OAUserId', mysql.BIGINT(display_width=20), server_default=sa.text('-1'), nullable=False),
    sa.Column('purposeId', mysql.BIGINT(display_width=20), server_default=sa.text('1'), nullable=False),
    sa.Column('respondentId', mysql.BIGINT(display_width=20), server_default=sa.text('1'), nullable=False),
    sa.Column('title', mysql.BIGINT(display_width=20), nullable=False),
    sa.Column('nickname', mysql.BIGINT(display_width=20), nullable=False),
    sa.Column('category', mysql.INTEGER(display_width=11), server_default=sa.text('-1'), nullable=False),
    sa.Column('description', mysql.BIGINT(display_width=20), nullable=False),
    sa.Column('instruction', mysql.BIGINT(display_width=20), nullable=False),
    sa.Column('final', mysql.TINYINT(display_width=4), server_default=sa.text('0'), nullable=False),
    sa.Column('version', mysql.INTEGER(display_width=11), server_default=sa.text('1'), nullable=False),
    sa.Column('parentId', mysql.BIGINT(display_width=20), server_default=sa.text('-1'), nullable=False),
    sa.Column('private', mysql.TINYINT(display_width=4), server_default=sa.text('0'), nullable=False),
    sa.Column('optionalFeedback', mysql.TINYINT(display_width=4), server_default=sa.text('1'), nullable=False),
    sa.Column('visualization', mysql.TINYINT(display_width=4), server_default=sa.text('0'), nullable=False, comment='0 = regular view of the answers, 1 = graph'),
    sa.Column('logo', sa.String(length=512), nullable=False),
    sa.Column('deleted', mysql.TINYINT(display_width=4), server_default=sa.text('0'), nullable=False),
    sa.Column('deletedBy', sa.String(length=255), nullable=False),
    sa.Column('creationDate', sa.DateTime(), nullable=False),
    sa.Column('createdBy', sa.String(length=255), nullable=False),
    sa.Column('lastUpdated', sa.TIMESTAMP(), server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'), nullable=False),
    sa.Column('updatedBy', sa.String(length=255), nullable=False),
    sa.Column('legacyName', sa.String(length=255), nullable=False, comment='This field is mandatory to make the app works during the migration process. This field must be removed once the migration of the legacy questionnaire will be done, the triggers stopped and the app changed to use the correct standards.'),
    sa.ForeignKeyConstraint(['description'], ['QuestionnaireDB.dictionary.contentId'], ),
    sa.ForeignKeyConstraint(['instruction'], ['QuestionnaireDB.dictionary.contentId'], ),
    sa.ForeignKeyConstraint(['nickname'], ['QuestionnaireDB.dictionary.contentId'], ),
    sa.ForeignKeyConstraint(['purposeId'], ['QuestionnaireDB.purpose.ID'], ),
    sa.ForeignKeyConstraint(['respondentId'], ['QuestionnaireDB.respondent.ID'], ),
    sa.ForeignKeyConstraint(['title'], ['QuestionnaireDB.dictionary.contentId'], ),
    sa.PrimaryKeyConstraint('ID'),
    schema='QuestionnaireDB'
    )
    op.create_index(op.f('ix_QuestionnaireDB_questionnaire_OAUserId'), 'questionnaire', ['OAUserId'], unique=False, schema='QuestionnaireDB')
    op.create_index(op.f('ix_QuestionnaireDB_questionnaire_deleted'), 'questionnaire', ['deleted'], unique=False, schema='QuestionnaireDB')
    op.create_index(op.f('ix_QuestionnaireDB_questionnaire_description'), 'questionnaire', ['description'], unique=False, schema='QuestionnaireDB')
    op.create_index(op.f('ix_QuestionnaireDB_questionnaire_instruction'), 'questionnaire', ['instruction'], unique=False, schema='QuestionnaireDB')
    op.create_index(op.f('ix_QuestionnaireDB_questionnaire_nickname'), 'questionnaire', ['nickname'], unique=False, schema='QuestionnaireDB')
    op.create_index(op.f('ix_QuestionnaireDB_questionnaire_parentId'), 'questionnaire', ['parentId'], unique=False, schema='QuestionnaireDB')
    op.create_index(op.f('ix_QuestionnaireDB_questionnaire_purposeId'), 'questionnaire', ['purposeId'], unique=False, schema='QuestionnaireDB')
    op.create_index(op.f('ix_QuestionnaireDB_questionnaire_respondentId'), 'questionnaire', ['respondentId'], unique=False, schema='QuestionnaireDB')
    op.create_index(op.f('ix_QuestionnaireDB_questionnaire_title'), 'questionnaire', ['title'], unique=False, schema='QuestionnaireDB')
    op.alter_column('alert', 'deletedBy',
               existing_type=mysql.VARCHAR(length=128),
               nullable=True,
               existing_comment='Username of the person who deleted the record')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('alert', 'deletedBy',
               existing_type=mysql.VARCHAR(length=128),
               nullable=False,
               existing_comment='Username of the person who deleted the record')
    op.drop_index(op.f('ix_QuestionnaireDB_questionnaire_title'), table_name='questionnaire', schema='QuestionnaireDB')
    op.drop_index(op.f('ix_QuestionnaireDB_questionnaire_respondentId'), table_name='questionnaire', schema='QuestionnaireDB')
    op.drop_index(op.f('ix_QuestionnaireDB_questionnaire_purposeId'), table_name='questionnaire', schema='QuestionnaireDB')
    op.drop_index(op.f('ix_QuestionnaireDB_questionnaire_parentId'), table_name='questionnaire', schema='QuestionnaireDB')
    op.drop_index(op.f('ix_QuestionnaireDB_questionnaire_nickname'), table_name='questionnaire', schema='QuestionnaireDB')
    op.drop_index(op.f('ix_QuestionnaireDB_questionnaire_instruction'), table_name='questionnaire', schema='QuestionnaireDB')
    op.drop_index(op.f('ix_QuestionnaireDB_questionnaire_description'), table_name='questionnaire', schema='QuestionnaireDB')
    op.drop_index(op.f('ix_QuestionnaireDB_questionnaire_deleted'), table_name='questionnaire', schema='QuestionnaireDB')
    op.drop_index(op.f('ix_QuestionnaireDB_questionnaire_OAUserId'), table_name='questionnaire', schema='QuestionnaireDB')
    op.drop_table('questionnaire', schema='QuestionnaireDB')
    op.drop_index(op.f('ix_QuestionnaireDB_respondent_title'), table_name='respondent', schema='QuestionnaireDB')
    op.drop_index(op.f('ix_QuestionnaireDB_respondent_description'), table_name='respondent', schema='QuestionnaireDB')
    op.drop_table('respondent', schema='QuestionnaireDB')
    op.drop_index(op.f('ix_QuestionnaireDB_purpose_title'), table_name='purpose', schema='QuestionnaireDB')
    op.drop_index(op.f('ix_QuestionnaireDB_purpose_description'), table_name='purpose', schema='QuestionnaireDB')
    op.drop_table('purpose', schema='QuestionnaireDB')
    op.drop_index(op.f('ix_QuestionnaireDB_language_name'), table_name='language', schema='QuestionnaireDB')
    op.drop_index(op.f('ix_QuestionnaireDB_language_deleted'), table_name='language', schema='QuestionnaireDB')
    op.drop_table('language', schema='QuestionnaireDB')
    op.drop_index(op.f('ix_QuestionnaireDB_dictionary_tableId'), table_name='dictionary', schema='QuestionnaireDB')
    op.drop_index(op.f('ix_QuestionnaireDB_dictionary_languageId'), table_name='dictionary', schema='QuestionnaireDB')
    op.drop_index(op.f('ix_QuestionnaireDB_dictionary_deleted'), table_name='dictionary', schema='QuestionnaireDB')
    op.drop_index(op.f('ix_QuestionnaireDB_dictionary_contentId'), table_name='dictionary', schema='QuestionnaireDB')
    op.drop_table('dictionary', schema='QuestionnaireDB')
    op.drop_table('definitionTable', schema='QuestionnaireDB')
    # ### end Alembic commands ###
