"""Add default value for alert deletedBy

Revision ID: 7ebe01c0c5e0
Revises: bcf300b3df7b
Create Date: 2023-05-19 16:57:01.636308

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7ebe01c0c5e0'
down_revision = 'bcf300b3df7b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('alert', 'deletedBy',
               existing_type=mysql.VARCHAR(length=128),
               nullable=True,
               existing_comment='Username of the person who deleted the record')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('alert', 'deletedBy',
               existing_type=mysql.VARCHAR(length=128),
               nullable=False,
               existing_comment='Username of the person who deleted the record')
