"""Add Username column to EducationalMaterialRating table

Revision ID: 83ccbdfcf3b5
Revises: 9f32d05833a5
Create Date: 2023-05-10 14:17:33.996075

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '83ccbdfcf3b5'
down_revision = '9f32d05833a5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Add Username column for the person who submitted an educational material rating"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('EducationalMaterialRating', sa.Column('Username', sa.String(length=255), server_default=sa.text("''"), nullable=False, comment='The username of the person who submitted an educational material rating.'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Drop Username column"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('EducationalMaterialRating', 'Username')
    # ### end Alembic commands ###
