"""Deprecate SessionId fields used to store Firebase tokens (QSCCD-244)

Revision ID: 9f32d05833a5
Revises: 75c66041e347
Create Date: 2023-04-26 17:30:33.369254

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9f32d05833a5'
down_revision = '75c66041e347'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('EducationalMaterialRating', 'SessionId',
               existing_type=mysql.TEXT(),
               server_default=sa.text("''"),
               comment='Deprecated',
               existing_nullable=False)
    op.alter_column('Feedback', 'SessionId',
               existing_type=mysql.TEXT(),
               server_default=sa.text("''"),
               comment='Deprecated',
               existing_nullable=False)
    op.alter_column('PatientActivityLog', 'SessionId',
               existing_type=mysql.TEXT(),
               server_default=sa.text("''"),
               comment='Deprecated',
               existing_nullable=False)
    op.alter_column('PatientDeviceIdentifier', 'SessionId',
               existing_type=mysql.TEXT(),
               server_default=sa.text("''"),
               comment='Deprecated',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('PatientDeviceIdentifier', 'SessionId',
               existing_type=mysql.TEXT(),
               server_default=None,
               comment=None,
               existing_comment='Deprecated',
               existing_nullable=False)
    op.alter_column('PatientActivityLog', 'SessionId',
               existing_type=mysql.TEXT(),
               server_default=None,
               comment=None,
               existing_comment='Deprecated',
               existing_nullable=False)
    op.alter_column('Feedback', 'SessionId',
               existing_type=mysql.TEXT(),
               server_default=None,
               comment=None,
               existing_comment='Deprecated',
               existing_nullable=False)
    op.alter_column('EducationalMaterialRating', 'SessionId',
               existing_type=mysql.TEXT(),
               server_default=None,
               comment=None,
               existing_comment='Deprecated',
               existing_nullable=False)
    # ### end Alembic commands ###
