-- SPDX-FileCopyrightText: Copyright (C) 2024 Opal Health Informatics Group at the Research Institute of the McGill University Health Centre <john.kildea@mcgill.ca>
--
-- SPDX-License-Identifier: AGPL-3.0-or-later

-- Disable system versioning in all tables for auditing purposes
-- Mariadb System Versioning: https://mariadb.com/kb/en/system-versioned-tables/
ALTER TABLE AppointmentCode DROP SYSTEM VERSIONING;
ALTER TABLE ClinicHub DROP SYSTEM VERSIONING;
ALTER TABLE ClinicResources DROP SYSTEM VERSIONING;
ALTER TABLE Cron DROP SYSTEM VERSIONING;
ALTER TABLE DiagnosisChapter DROP SYSTEM VERSIONING;
ALTER TABLE DiagnosisCode DROP SYSTEM VERSIONING;
ALTER TABLE DiagnosisSubcode DROP SYSTEM VERSIONING;
ALTER TABLE ExamRoom DROP SYSTEM VERSIONING;
ALTER TABLE Hospital DROP SYSTEM VERSIONING;
ALTER TABLE Insurance DROP SYSTEM VERSIONING;
ALTER TABLE IntermediateVenue DROP SYSTEM VERSIONING;
ALTER TABLE MediVisitAppointmentList DROP SYSTEM VERSIONING;
ALTER TABLE Patient DROP SYSTEM VERSIONING;
ALTER TABLE PatientDiagnosis DROP SYSTEM VERSIONING;
ALTER TABLE PatientHospitalIdentifier DROP SYSTEM VERSIONING;
ALTER TABLE PatientInsuranceIdentifier DROP SYSTEM VERSIONING;
ALTER TABLE PatientLocation DROP SYSTEM VERSIONING;
ALTER TABLE PatientLocationMH DROP SYSTEM VERSIONING;
ALTER TABLE PatientMeasurement DROP SYSTEM VERSIONING;
ALTER TABLE Profile DROP SYSTEM VERSIONING;
ALTER TABLE ProfileColumnDefinition DROP SYSTEM VERSIONING;
ALTER TABLE ProfileColumns DROP SYSTEM VERSIONING;
ALTER TABLE ProfileOptions DROP SYSTEM VERSIONING;
ALTER TABLE SmsAppointment DROP SYSTEM VERSIONING;
ALTER TABLE SmsMessage DROP SYSTEM VERSIONING;
ALTER TABLE SpecialityGroup DROP SYSTEM VERSIONING;
ALTER TABLE TEMP_PatientQuestionnaireReview DROP SYSTEM VERSIONING;
