-- SPDX-FileCopyrightText: Copyright (C) 2023 Opal Health Informatics Group at the Research Institute of the McGill University Health Centre <john.kildea@mcgill.ca>
--
-- SPDX-License-Identifier: AGPL-3.0-or-later

-- Enable system versioning in all tables for auditing purposes
-- Mariadb System Versioning: https://mariadb.com/kb/en/system-versioned-tables/
ALTER TABLE AppointmentCode ADD SYSTEM VERSIONING;
ALTER TABLE ClinicHub ADD SYSTEM VERSIONING;
ALTER TABLE ClinicResources ADD SYSTEM VERSIONING;
ALTER TABLE Cron ADD SYSTEM VERSIONING;
ALTER TABLE DiagnosisChapter ADD SYSTEM VERSIONING;
ALTER TABLE DiagnosisCode ADD SYSTEM VERSIONING;
ALTER TABLE DiagnosisSubcode ADD SYSTEM VERSIONING;
ALTER TABLE ExamRoom ADD SYSTEM VERSIONING;
ALTER TABLE Hospital ADD SYSTEM VERSIONING;
ALTER TABLE Insurance ADD SYSTEM VERSIONING;
ALTER TABLE IntermediateVenue ADD SYSTEM VERSIONING;
ALTER TABLE MediVisitAppointmentList ADD SYSTEM VERSIONING;
ALTER TABLE Patient ADD SYSTEM VERSIONING;
ALTER TABLE PatientDiagnosis ADD SYSTEM VERSIONING;
ALTER TABLE PatientHospitalIdentifier ADD SYSTEM VERSIONING;
ALTER TABLE PatientInsuranceIdentifier ADD SYSTEM VERSIONING;
ALTER TABLE PatientLocation ADD SYSTEM VERSIONING;
ALTER TABLE PatientLocationMH ADD SYSTEM VERSIONING;
ALTER TABLE PatientMeasurement ADD SYSTEM VERSIONING;
ALTER TABLE Profile ADD SYSTEM VERSIONING;
ALTER TABLE ProfileColumnDefinition ADD SYSTEM VERSIONING;
ALTER TABLE ProfileColumns ADD SYSTEM VERSIONING;
ALTER TABLE ProfileOptions ADD SYSTEM VERSIONING;
ALTER TABLE SmsAppointment ADD SYSTEM VERSIONING;
ALTER TABLE SmsMessage ADD SYSTEM VERSIONING;
ALTER TABLE SpecialityGroup ADD SYSTEM VERSIONING;
ALTER TABLE TEMP_PatientQuestionnaireReview ADD SYSTEM VERSIONING;
