CREATE TABLE IF NOT EXISTS `TestControl` (
  `TestControlSerNum` int(11) NOT NULL AUTO_INCREMENT,
  `Name_EN` varchar(200) NOT NULL,
  `Name_FR` varchar(200) NOT NULL,
  `Description_EN` text NOT NULL,
  `Description_FR` text NOT NULL,
  `Group_EN` varchar(200) NOT NULL,
  `Group_FR` varchar(200) NOT NULL,
  `SourceDatabaseSerNum` int(11) NOT NULL DEFAULT 1,
  `EducationalMaterialControlSerNum` int(11) DEFAULT NULL,
  `PublishFlag` int(11) NOT NULL,
  `DateAdded` datetime NOT NULL,
  `LastPublished` datetime NOT NULL DEFAULT '2002-01-01 00:00:00',
  `LastUpdatedBy` int(11) DEFAULT NULL,
  `LastUpdated` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `URL_EN` varchar(2000) NOT NULL,
  `URL_FR` varchar(2000) NOT NULL,
  `SessionId` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`TestControlSerNum`),
  KEY `SourceDatabaseSerNum` (`SourceDatabaseSerNum`),
  KEY `EducationalMaterialControlSerNum` (`EducationalMaterialControlSerNum`),
  KEY `LastUpdatedBy` (`LastUpdatedBy`),
  CONSTRAINT `TestControl_ibfk_1` FOREIGN KEY (`SourceDatabaseSerNum`) REFERENCES `SourceDatabase` (`SourceDatabaseSerNum`) ON UPDATE CASCADE,
  CONSTRAINT `TestControl_ibfk_2` FOREIGN KEY (`LastUpdatedBy`) REFERENCES `OAUser` (`OAUserSerNum`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `TestControl_ibfk_3` FOREIGN KEY (`EducationalMaterialControlSerNum`) REFERENCES `EducationalMaterialControl` (`EducationalMaterialControlSerNum`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `TestExpression` (
  `TestExpressionSerNum` int(11) NOT NULL AUTO_INCREMENT,
  `TestControlSerNum` int(11) DEFAULT NULL,
  `TestCode` varchar(30) NOT NULL DEFAULT '',
  `ExpressionName` varchar(100) NOT NULL,
  `DateAdded` datetime NOT NULL,
  `LastPublished` datetime NOT NULL DEFAULT '2000-01-01 00:00:00',
  `LastUpdatedBy` int(11) DEFAULT NULL,
  `SourceDatabaseSerNum` int(11) NOT NULL DEFAULT 4,
  `LastUpdated` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `SessionId` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`TestExpressionSerNum`),
  UNIQUE KEY `TestCode` (`TestCode`,`SourceDatabaseSerNum`),
  KEY `TestResultControlSerNum` (`TestControlSerNum`),
  KEY `LastUpdatedBy` (`LastUpdatedBy`),
  KEY `TestExpression_ibfk_1` (`SourceDatabaseSerNum`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `TestGroupExpression` (
  `TestGroupExpressionSerNum` int(11) NOT NULL AUTO_INCREMENT,
  `TestControlSerNum` bigint(20) DEFAULT NULL,
  `TestCode` varchar(30) NOT NULL DEFAULT '',
  `ExpressionName` varchar(100) NOT NULL,
  `DateAdded` datetime NOT NULL,
  `LastPublished` datetime NOT NULL DEFAULT '2000-01-01 00:00:00',
  `LastUpdatedBy` int(11) DEFAULT NULL,
  `SourceDatabaseSerNum` int(11) NOT NULL DEFAULT 4,
  `LastUpdated` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `SessionId` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`TestGroupExpressionSerNum`),
  UNIQUE KEY `TestCode` (`TestCode`,`SourceDatabaseSerNum`),
  KEY `TestResultControlSerNum` (`TestControlSerNum`),
  KEY `LastUpdatedBy` (`LastUpdatedBy`),
  KEY `TestExpression_ibfk_1` (`SourceDatabaseSerNum`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `TestResultNotificationProcessingLog` (
  `TestResultNotificationResultLogId` int(11) NOT NULL AUTO_INCREMENT,
  `TestResultNotificationQueueId` int(11) NOT NULL,
  `Status` enum('COMPLETED','PENDING','MAX_ATTEMPTS_REACHED') NOT NULL,
  `InsertedRows` int(11) NOT NULL,
  `UpdatedRows` int(11) NOT NULL,
  `ProcessingDateTime` datetime DEFAULT NULL,
  `ProcessingAttemptNumber` int(11) DEFAULT NULL,
  `ProcessingError` text DEFAULT NULL,
  `ModificationAction` varchar(20) NOT NULL,
  `LastUpdated` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`TestResultNotificationResultLogId`),
  KEY `FK_Test_Result_Notification_Queue_Id` (`TestResultNotificationQueueId`),
  CONSTRAINT `FK_Test_Result_Notification_Queue_Id` FOREIGN KEY (`TestResultNotificationQueueId`) REFERENCES `TestResultNotificationQueue` (`TestResultNotificationQueueId`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `TestResultNotificationQueue` (
  `TestResultNotificationQueueId` int(11) NOT NULL AUTO_INCREMENT,
  `PatientSerNum` int(11) DEFAULT NULL,
  `Mrn` varchar(20) NOT NULL,
  `Site` varchar(20) NOT NULL,
  `Ramq` varchar(40) NOT NULL,
  `NotificationId` varchar(20) DEFAULT NULL,
  `SpecimenDateTime` datetime NOT NULL,
  `ResultDateTime` datetime NOT NULL,
  `Status` enum('COMPLETED','PENDING','MAX_ATTEMPTS_REACHED') NOT NULL DEFAULT 'PENDING',
  `ImportDateTime` datetime NOT NULL,
  `ProcessingAttemptNumber` int(11) NOT NULL DEFAULT 0,
  `LastProcessingDateTime` datetime DEFAULT NULL,
  `InsertedRows` int(11) NOT NULL DEFAULT 0,
  `UpdatedRows` int(11) NOT NULL DEFAULT 0,
  `LastProcessingError` text DEFAULT NULL,
  `LastUpdated` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`TestResultNotificationQueueId`),
  KEY `FK_PatientSerNum` (`PatientSerNum`),
  CONSTRAINT `FK_PatientSerNum` FOREIGN KEY (`PatientSerNum`) REFERENCES `Patient` (`PatientSerNum`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `TestResult` (
  `TestResultSerNum` int(11) NOT NULL AUTO_INCREMENT,
  `CronLogSerNum` int(11) DEFAULT NULL,
  `TestResultGroupSerNum` int(11) NOT NULL,
  `TestResultControlSerNum` int(11) NOT NULL,
  `TestResultExpressionSerNum` int(11) NOT NULL,
  `PatientSerNum` int(11) NOT NULL,
  `SourceDatabaseSerNum` int(11) NOT NULL,
  `TestResultAriaSer` varchar(100) NOT NULL,
  `ComponentName` varchar(30) NOT NULL,
  `FacComponentName` varchar(30) NOT NULL,
  `AbnormalFlag` varchar(5) NOT NULL,
  `TestDate` datetime NOT NULL,
  `MaxNorm` float NOT NULL,
  `MinNorm` float NOT NULL,
  `ApprovedFlag` varchar(5) NOT NULL,
  `TestValue` float NOT NULL,
  `TestValueString` varchar(400) NOT NULL,
  `UnitDescription` varchar(40) NOT NULL,
  `ValidEntry` varchar(5) NOT NULL,
  `DateAdded` datetime NOT NULL,
  `ReadStatus` int(11) NOT NULL,
  `LastUpdated` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`TestResultSerNum`),
  KEY `PatientSerNum` (`PatientSerNum`),
  KEY `TestResultAriaSer` (`TestResultAriaSer`),
  KEY `TestResultControlSerNum` (`TestResultControlSerNum`),
  KEY `SourceDatabaseSerNum` (`SourceDatabaseSerNum`),
  KEY `CronLogSerNum` (`CronLogSerNum`),
  KEY `TestResultExpressionSerNum` (`TestResultExpressionSerNum`),
  KEY `TestResultGroupSerNum` (`TestResultGroupSerNum`),
  CONSTRAINT `TestResult_ibfk_1` FOREIGN KEY (`PatientSerNum`) REFERENCES `Patient` (`PatientSerNum`) ON UPDATE CASCADE,
  CONSTRAINT `TestResult_ibfk_2` FOREIGN KEY (`CronLogSerNum`) REFERENCES `CronLog` (`CronLogSerNum`) ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `TestResultAdditionalLinks` (
  `TestResultAdditionalLinksSerNum` int(11) NOT NULL AUTO_INCREMENT,
  `TestResultControlSerNum` int(11) NOT NULL,
  `Name_EN` varchar(1028) NOT NULL,
  `Name_FR` varchar(1028) NOT NULL,
  `URL_EN` varchar(2056) NOT NULL,
  `URL_FR` varchar(2056) NOT NULL,
  `DateAdded` datetime NOT NULL,
  `LastUpdated` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`TestResultAdditionalLinksSerNum`),
  KEY `TestResultControlSerNum` (`TestResultControlSerNum`),
  CONSTRAINT `TestResultAdditionalLinks_ibfk_1` FOREIGN KEY (`TestResultControlSerNum`) REFERENCES `TestResultControl` (`TestResultControlSerNum`) ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `TestResultControl` (
  `TestResultControlSerNum` int(11) NOT NULL AUTO_INCREMENT,
  `Name_EN` varchar(200) NOT NULL,
  `Name_FR` varchar(200) NOT NULL,
  `Description_EN` text NOT NULL,
  `Description_FR` text NOT NULL,
  `Group_EN` varchar(200) NOT NULL,
  `Group_FR` varchar(200) NOT NULL,
  `SourceDatabaseSerNum` int(11) NOT NULL DEFAULT 1,
  `EducationalMaterialControlSerNum` int(11) DEFAULT NULL,
  `PublishFlag` int(11) NOT NULL,
  `DateAdded` datetime NOT NULL,
  `LastPublished` datetime NOT NULL DEFAULT '2002-01-01 00:00:00',
  `LastUpdatedBy` int(11) DEFAULT NULL,
  `LastUpdated` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `URL_EN` varchar(2000) NOT NULL,
  `URL_FR` varchar(2000) NOT NULL,
  `SessionId` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`TestResultControlSerNum`),
  KEY `SourceDatabaseSerNum` (`SourceDatabaseSerNum`),
  KEY `EducationalMaterialControlSerNum` (`EducationalMaterialControlSerNum`),
  KEY `LastUpdatedBy` (`LastUpdatedBy`),
  CONSTRAINT `TestResultControl_ibfk_1` FOREIGN KEY (`SourceDatabaseSerNum`) REFERENCES `SourceDatabase` (`SourceDatabaseSerNum`) ON UPDATE CASCADE,
  CONSTRAINT `TestResultControl_ibfk_2` FOREIGN KEY (`LastUpdatedBy`) REFERENCES `OAUser` (`OAUserSerNum`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `TestResultControl_ibfk_3` FOREIGN KEY (`EducationalMaterialControlSerNum`) REFERENCES `EducationalMaterialControl` (`EducationalMaterialControlSerNum`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `TestResultControlMH` (
  `TestResultControlSerNum` int(11) NOT NULL,
  `RevSerNum` int(11) NOT NULL AUTO_INCREMENT,
  `Name_EN` varchar(200) NOT NULL,
  `Name_FR` varchar(200) NOT NULL,
  `Description_EN` text NOT NULL,
  `Description_FR` text NOT NULL,
  `Group_EN` varchar(200) NOT NULL,
  `Group_FR` varchar(200) NOT NULL,
  `SourceDatabaseSerNum` int(11) NOT NULL DEFAULT 1,
  `EducationalMaterialControlSerNum` int(11) DEFAULT NULL,
  `PublishFlag` int(11) NOT NULL,
  `DateAdded` datetime NOT NULL,
  `LastPublished` datetime NOT NULL DEFAULT '2002-01-01 00:00:00',
  `LastUpdatedBy` int(11) DEFAULT NULL,
  `LastUpdated` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `ModificationAction` varchar(25) NOT NULL,
  `URL_EN` varchar(2000) DEFAULT NULL,
  `URL_FR` varchar(2000) DEFAULT NULL,
  `SessionId` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`TestResultControlSerNum`,`RevSerNum`),
  KEY `SourceDatabaseSerNum` (`SourceDatabaseSerNum`),
  KEY `LastUpdatedBy` (`LastUpdatedBy`),
  KEY `EducationalMaterialControlSerNum` (`EducationalMaterialControlSerNum`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `TestResultExpression` (
  `TestResultExpressionSerNum` int(11) NOT NULL AUTO_INCREMENT,
  `TestResultControlSerNum` int(11) NOT NULL,
  `ExpressionName` varchar(100) NOT NULL,
  `DateAdded` datetime NOT NULL,
  `LastPublished` datetime NOT NULL DEFAULT '2000-01-01 00:00:00',
  `LastUpdatedBy` int(11) DEFAULT NULL,
  `LastUpdated` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `SessionId` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`TestResultExpressionSerNum`),
  UNIQUE KEY `ExpressionName` (`ExpressionName`),
  KEY `TestResultControlSerNum` (`TestResultControlSerNum`),
  KEY `LastUpdatedBy` (`LastUpdatedBy`),
  CONSTRAINT `TestResultExpression_ibfk_1` FOREIGN KEY (`TestResultControlSerNum`) REFERENCES `TestResultControl` (`TestResultControlSerNum`) ON UPDATE CASCADE,
  CONSTRAINT `TestResultExpression_ibfk_2` FOREIGN KEY (`LastUpdatedBy`) REFERENCES `OAUser` (`OAUserSerNum`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `TestResultExpressionMH` (
  `TestResultControlSerNum` int(11) NOT NULL,
  `ExpressionName` varchar(100) NOT NULL,
  `RevSerNum` int(11) NOT NULL AUTO_INCREMENT,
  `DateAdded` datetime NOT NULL,
  `ModificationAction` varchar(25) NOT NULL,
  `LastPublished` datetime NOT NULL DEFAULT '2000-01-01 00:00:00',
  `LastUpdatedBy` int(11) DEFAULT NULL,
  `SessionId` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ExpressionName`,`RevSerNum`),
  KEY `TestResultControlSerNum` (`TestResultControlSerNum`),
  KEY `LastUpdatedBy` (`LastUpdatedBy`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `TestResultMH` (
  `TestResultSerNum` int(11) NOT NULL,
  `TestResultRevSerNum` int(11) NOT NULL AUTO_INCREMENT,
  `CronLogSerNum` int(11) DEFAULT NULL,
  `TestResultGroupSerNum` int(11) NOT NULL,
  `TestResultExpressionSerNum` int(11) NOT NULL,
  `PatientSerNum` int(11) NOT NULL,
  `SourceDatabaseSerNum` int(11) NOT NULL,
  `TestResultAriaSer` varchar(100) NOT NULL,
  `ComponentName` varchar(30) NOT NULL,
  `FacComponentName` varchar(30) NOT NULL,
  `AbnormalFlag` varchar(5) NOT NULL,
  `TestDate` datetime NOT NULL,
  `MaxNorm` float NOT NULL,
  `MinNorm` float NOT NULL,
  `ApprovedFlag` varchar(5) NOT NULL,
  `TestValue` float NOT NULL,
  `TestValueString` varchar(400) NOT NULL,
  `UnitDescription` varchar(40) NOT NULL,
  `ValidEntry` varchar(5) NOT NULL,
  `DateAdded` datetime NOT NULL,
  `ReadStatus` int(11) NOT NULL,
  `ModificationAction` varchar(25) NOT NULL,
  PRIMARY KEY (`TestResultSerNum`,`TestResultRevSerNum`),
  KEY `PatientSerNum` (`PatientSerNum`),
  KEY `TestResultAriaSer` (`TestResultAriaSer`),
  KEY `SourceDatabaseSerNum` (`SourceDatabaseSerNum`),
  KEY `TestResultExpressionSerNum` (`TestResultExpressionSerNum`),
  KEY `CronLogSerNum` (`CronLogSerNum`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `PatientTestResult` (
  `PatientTestResultSerNum` int(11) NOT NULL AUTO_INCREMENT,
  `TestGroupExpressionSerNum` int(11) DEFAULT NULL,
  `TestExpressionSerNum` int(11) NOT NULL,
  `PatientSerNum` int(11) NOT NULL,
  `AbnormalFlag` varchar(10) NOT NULL,
  `SequenceNum` int(11) DEFAULT NULL COMMENT 'Order of Lab Tests in which they should be displayed',
  `CollectedDateTime` datetime NOT NULL,
  `ResultDateTime` datetime NOT NULL,
  `NormalRangeMin` float DEFAULT NULL,
  `NormalRangeMax` float DEFAULT NULL,
  `NormalRange` varchar(30) NOT NULL DEFAULT '',
  `TestValueNumeric` float DEFAULT NULL,
  `TestValue` varchar(255) NOT NULL,
  `UnitDescription` varchar(40) NOT NULL,
  `DateAdded` datetime NOT NULL,
  `ReadStatus` int(11) NOT NULL,
  `LastUpdated` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`PatientTestResultSerNum`),
  UNIQUE KEY `PatientTestCodeTestDate` (`PatientSerNum`,`TestExpressionSerNum`,`CollectedDateTime`),
  KEY `PatientSerNum` (`PatientSerNum`),
  KEY `TestResultExpressionSerNum` (`TestExpressionSerNum`),
  KEY `TestResultGroupSerNum` (`TestGroupExpressionSerNum`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
