CREATE DATABASE IF NOT EXISTS `OpalDB` /*!40100 DEFAULT CHARACTER SET latin1 */;
CREATE DATABASE IF NOT EXISTS `QuestionnaireDB` /*!40100 DEFAULT CHARACTER SET utf8 */;
CREATE DATABASE IF NOT EXISTS `OpalReportDB` /*!40100 DEFAULT CHARACTER SET utf8 */;
CREATE DATABASE IF NOT EXISTS `OrmsDatabase` /*!40100 DEFAULT CHARACTER SET latin1 */;
CREATE DATABASE IF NOT EXISTS `OrmsLog` /*!40100 DEFAULT CHARACTER SET latin1 */;
