CREATE DATABASE IF NOT EXISTS `OpalDB` /*!40100 DEFAULT CHARACTER SET latin1 */;
USE `OpalDB`;

CREATE DATABASE IF NOT EXISTS `QuestionnaireDB` /*!40100 DEFAULT CHARACTER SET utf8 */;
USE `QuestionnaireDB`;

CREATE DATABASE IF NOT EXISTS `registerdb` /*!40100 DEFAULT CHARACTER SET utf8 */;
USE `registerdb`;