#!/bin/bash

MYSQL_PWD=$MARIADB_ROOT_PASSWORD mysql -uroot -hlocalhost << EOF
GRANT ALL PRIVILEGES ON \`OpalDB\`.* TO \`$MARIADB_USER\`@\`%\`;
GRANT ALL PRIVILEGES ON \`QuestionnaireDB\`.* TO \`$MARIADB_USER\`@\`%\`;
GRANT ALL PRIVILEGES ON \`registerdb\`.* TO \`$MARIADB_USER\`@\`%\`;
CREATE USER \`$MARIADB_GUEST_USER\`@\`%\` IDENTIFIED BY '$MARIADB_GUEST_PASSWORD';
EOF