CREATE TABLE IF NOT EXISTS `Doctor` (
  `DoctorSerNum` int(11) NOT NULL AUTO_INCREMENT,
  `ResourceSerNum` int(11) NOT NULL,
  `SourceDatabaseSerNum` int(11) NOT NULL,
  `DoctorAriaSer` int(20) NOT NULL,
  `FirstName` varchar(100) NOT NULL,
  `LastName` varchar(100) NOT NULL,
  `Role` varchar(100) NOT NULL,
  `Workplace` varchar(100) NOT NULL,
  `Email` text DEFAULT NULL,
  `Phone` bigint(20) DEFAULT NULL,
  `Address` text DEFAULT NULL,
  `ProfileImage` varchar(255) NOT NULL,
  `LastUpdated` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `BIO_EN` text DEFAULT NULL,
  `BIO_FR` text DEFAULT NULL,
  PRIMARY KEY (`DoctorSerNum`),
  KEY `DoctorAriaSer` (`DoctorAriaSer`),
  KEY `SourceDatabaseSerNum` (`SourceDatabaseSerNum`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `DoctorMH` (
  `DoctorSerNum` int(11) NOT NULL,
  `DoctorRevSerNum` int(11) NOT NULL AUTO_INCREMENT,
  `ResourceSerNum` int(11) NOT NULL,
  `SourceDatabaseSerNum` int(11) NOT NULL,
  `DoctorAriaSer` int(20) NOT NULL,
  `FirstName` varchar(100) NOT NULL,
  `LastName` varchar(100) NOT NULL,
  `Role` varchar(100) NOT NULL,
  `Workplace` varchar(100) NOT NULL,
  `Email` text DEFAULT NULL,
  `Phone` int(20) DEFAULT NULL,
  `Address` text DEFAULT NULL,
  `ProfileImage` varchar(255) NOT NULL,
  `ModificationAction` varchar(25) NOT NULL,
  `LastUpdated` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `BIO_EN` text DEFAULT NULL,
  `BIO_FR` text DEFAULT NULL,
  PRIMARY KEY (`DoctorSerNum`,`DoctorRevSerNum`),
  KEY `SourceDatabaseSerNum` (`SourceDatabaseSerNum`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;